import type { Metadata } from "next";
import { Inter, Poppins, Noto_Sans_TC } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: ["700"]  ,subsets: ["latin"] });
const notoSansTC = Noto_Sans_TC({ weight: ["200", "500", "700"], subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${poppins.className} ${notoSansTC.className}`}>{children}</body>
    </html>
  );
}
